In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("resources/zip_code_database.csv")

In [72]:
# df.head(11510)

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population_2015
0,501,UNIQUE,0,Holtsville,NaN,I R S Service Center,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,562
1,544,UNIQUE,0,Holtsville,NaN,Irs Service Center,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,0
2,601,STANDARD,0,Adjuntas,NaN,"Colinas Del Gigante, Jard De Adjuntas, Urb San...",PR,Adjuntas Municipio,America/Puerto_Rico,"787,939",NaN,US,18.16,-66.72,0
3,602,STANDARD,0,Aguada,NaN,"Alts De Aguada, Bo Guaniquilla, Comunidad Las ...",PR,Aguada Municipio,America/Puerto_Rico,"787,939",NaN,US,18.38,-67.18,0
4,603,STANDARD,0,Aguadilla,Ramey,"Bda Caban, Bda Esteves, Bo Borinquen, Bo Ceiba...",PR,Aguadilla Municipio,America/Puerto_Rico,787,NaN,US,18.43,-67.15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11505,27613,STANDARD,0,Raleigh,NaN,NaN,NC,Wake County,America/New_York,919,NaN,US,35.93,-78.71,44050
11506,27614,STANDARD,0,Raleigh,NaN,North Hills,NC,Wake County,America/New_York,919,NaN,US,35.95,-78.62,33190
11507,27615,STANDARD,0,Raleigh,NaN,NaN,NC,Wake County,America/New_York,919,NaN,US,35.90,-78.64,41850
11508,27616,STANDARD,0,Raleigh,Brentwood,NaN,NC,Wake County,America/New_York,919,NaN,US,35.87,-78.54,48670
11509,27617,STANDARD,0,Raleigh,NaN,NaN,NC,Wake County,America/New_York,919,NaN,US,35.91,-78.77,18050

In [73]:
# df.columns

Index(['zip', 'type', 'decommissioned', 'primary_city', 'acceptable_cities',
       'unacceptable_cities', 'state', 'county', 'timezone', 'area_codes',
       'world_region', 'country', 'latitude', 'longitude',
       'irs_estimated_population_2015'],
      dtype='object')

In [74]:
zip_frame = df.loc[lambda df: df['state'] == 'NC']
zip_frame = zip_frame[['zip', 'latitude', 'longitude']].reset_index()

In [95]:
zip_frame.head()

     zip  latitude  longitude
0  25911     37.76     -81.17
1  27601     35.77     -78.63
2  27602     35.82     -78.65
3  27603     35.66     -78.65
4  27604     35.82     -78.56

In [97]:
zip_list = zip_frame['zip'].tolist()
zip_list[0]

25911

In [8]:
def make_zip_list(state):
    ''' Make a list of zip codes in the specified state.
        
        :param state: the two-letter abreviation of the state whose zip codes you'd like listed
        :type state: string
    '''
    import pandas as pd
    
    df = pd.read_csv("resources/zip_code_database.csv")
    # Make a datafram from the rows with the specified state and write the 'zip' column to a list 
    zip_list = df.loc[lambda df: df['state'] == f'{state.upper()}']['zip'].tolist()
    return(zip_list)
#     zip_frame = zip_frame[['zip', 'latitude', 'longitude']].reset_index()

In [122]:
def write_list_to_file(zip_list, filename):
    """Write the list to csv file."""

    with open(filename, "w") as z_list:
        z_list.write(",".join(str(z) for z in zip_list))
# #         for entry in zip_list:
#             z_list.write(str(entry))
#             z_list.write(",")
            
filename = 'zip_list.csv'

In [123]:
def read_list_from_file(filename):
    """Write the list to csv file."""

    with open(filename, "r") as z_list:
        return z_list.read().strip().split(',')

In [9]:
make_zip_list('Nc')

[]

In [125]:
write_list_to_file(zip_list, filename)